server:
  port: 10013 #服务端口
spring:
  application:
    name: gateway #指定服务名
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #5秒间隔获取服务列表
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
#zuul:
#  routes:
#    user-service: # 这里是路由id，随意写
#      path: /user-service/** # 这里是映射路径
#      serviceId: user-service # 指定服务名称

#zuul:
#  routes:
#    user-service: /user-service/** # 这里是映射路径
#day0308 http://localhost:10010/user-service/user/1
#day0308 http://localhost:10010/consumer-service/consumer/1
#day0306 http://localhost:10010/user-service匹配
#day0306 http://localhost:10010/user-service/user/1
#day0306 http://127.0.0.1:8081/user/1

#day0313
zuul:
  prefix: /api
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false #不截取/user

#day0313  http://localhost:10010/user/1
#day0313  http://localhost:10010/api/user/1